#!/usr/bin/env python3
"""
export-pipeline.py — Export Master Skill Suite 8-stage pipeline as Mermaid diagram.

Outputs a Mermaid flowchart showing the full 8-stage pipeline:
    Explorer → Miner → Architect → Gatekeeper → Planner → Builder → Reviewer → Tester → Indexer

Includes META gate annotations, fallback routes (F3/F8), and ver-3 color scheme.

Usage:
    python export-pipeline.py [--output <file.md>]
"""

import argparse
from pathlib import Path
from datetime import datetime


def generate_pipeline_diagram() -> str:
    """Generate the 8-stage Master Skill Suite Pipeline diagram in Mermaid format."""

    diagram = """# Master Skill Suite Pipeline — 8 Stages

> Generated by skill-architect ver-3 | {date}
> Upstream: skill-explorer, skill-knowledge-miner
> Downstream: production-quality-gatekeeper, skill-planner, skill-builder, production-code-reviewer, sandbox-tester, indexer

```mermaid
flowchart LR
    subgraph Pipeline[8-Stage Master Skill Suite Pipeline]
        direction LR

        E[<b>Stage 0</b><br/>Explorer] -->|exploration.md<br/>criteria.md| KM
        KM[<b>Stage 0.5</b><br/>Knowledge Miner] -->|domain-handbook.md| A

        A[<b>Stage 1</b><br/>Architect] -->|design.md<br/>drc.yaml| QG

        QG[<b>Stage 1.5</b><br/>Gatekeeper] -->|PASS| P
        QG -->|F3 FAIL → revise| A

        P[<b>Stage 2</b><br/>Planner] -->|todo.md| B
        P -->|F8 drift → re-elicit| A

        B[<b>Stage 3</b><br/>Builder] -->|skill files| R

        R[<b>Stage 3.5</b><br/>Reviewer] -->|review report| T

        T[<b>Stage 4</b><br/>Tester] -->|verification.md| I

        I[<b>Stage 5</b><br/>Indexer] -->|llms.txt<br/>README.md| Deploy([Deploy])

        E -->|criteria.md| A
    end

    subgraph META[META Quality Gates]
        M1[META-1<br/>Structural]
        M2[META-2<br/>Semantic Depth]
        M3[META-3<br/>Mechanical]
    end

    A -.->|validates| M1
    A -.->|validates| M2
    A -.->|validates| M3
    M1 -->|≥0.80| QG
    M2 -->|≥0.80| QG
    M3 -->|1.00| QG

    style E fill:#e8f5e9,stroke:#2e7d32,stroke-width:2px
    style KM fill:#c8e6c9,stroke:#388e3c,stroke-width:2px
    style A fill:#ffcdd2,stroke:#e53935,stroke-width:3px
    style QG fill:#fff9c4,stroke:#fbc02d,stroke-width:2px
    style P fill:#bbdefb,stroke:#1565c0,stroke-width:2px
    style B fill:#90caf9,stroke:#1976d2,stroke-width:2px
    style R fill:#e1f5fe,stroke:#01579b,stroke-width:2px
    style T fill:#f3e5f5,stroke:#7b1fa2,stroke-width:2px
    style I fill:#fff3e0,stroke:#ef6c00,stroke-width:2px
    style M1 fill:#e8eaf6,stroke:#3949ab
    style M2 fill:#e8eaf6,stroke:#3949ab
    style M3 fill:#e8eaf6,stroke:#3949ab
    style Deploy fill:#f9f9f9,stroke:#333,stroke-width:4px
```

## Pipeline Stages

| Stage | Skill | Input | Output | META Gate |
|-------|-------|-------|--------|-----------|
| 0 | skill-explorer | Domain raw materials | exploration.md, criteria.md | — |
| 0.5 | skill-knowledge-miner | Exploration output | domain-handbook.md | — |
| 1 | **skill-architect** | exploration.md + domain-handbook.md + criteria.md | design.md + drc.yaml | META-1, META-2, META-3 |
| 1.5 | production-quality-gatekeeper | design.md + drc.yaml | quality-matrix.yaml | Gate passes |
| 2 | skill-planner | design.md + quality-matrix.yaml | todo.md | Planner tasks |
| 3 | skill-builder | design.md + todo.md | skill files | Builder verification |
| 3.5 | production-code-reviewer | skill files | review-report.md | Code quality |
| 4 | sandbox-tester | skill files + review-report | verification.md (PASS/FAIL) | Test results |
| 5 | indexer | verification.md | llms.txt, README.md | Registration |

## Fallback Routes

- **F3**: Gatekeeper validation fail → architect revise (loop back to Stage 1)
- **F8**: Drift detected during planning → architect re-elicit (loop back to Stage 1)

## META Gate Descriptions

| Gate | Components | Threshold | Verification |
|------|-----------|-----------|--------------|
| META-1 Structural | domain anchor, 6 phases, 7-zone table, frontmatter | ≥0.80 | Regex/script on design.md |
| META-2 Semantic Depth | S1≥5/phase, S2≥4/aspect, S3≥2 stakeholders, S4 constraints | AND ≥0.80 | Count per phase |
| META-3 Mechanical | ARCH-1/2/3/4 PASS, BUILD-3.1 ≤700t, zero placeholder | 1.00 (ALL) | Automated scan |

---

*For more details, see skills/ver-3/skill-architect/SKILL.md*
"""

    return diagram.format(date=datetime.now().strftime("%Y-%m-%d %H:%M"))


def main():
    parser = argparse.ArgumentParser(description="8-Stage Pipeline Diagram Generator")
    parser.add_argument("--output", "-o", help="Output markdown file path", default=None)
    parsed = parser.parse_args()
    output_file = parsed.output

    diagram = generate_pipeline_diagram()

    if output_file:
        Path(output_file).write_text(diagram, encoding="utf-8")
        print(f"Pipeline diagram exported to: {output_file}")
    else:
        print(diagram)

    return 0


if __name__ == "__main__":
    sys.exit(main())
